### ISSUE TITLE
Can we use SHA2 as well?

### ISSUE THREAD

**Issue by DocFreeman** [notpeter/apple-installer-checksums#10]
My understanding is that SHA1 is pretty safe, but a determined (and extremely well funded) group could probably compromise it. Why not preemptively move to SHA2 for important things like OS verification? The web already seems to be moving towards it, so I think it would be a good time to start. No one else seems to be talking about changing to it for file checking yet.

**Comment by dodekeract** [comment]
:+1: I'd also suggest to add as many different hash algorithms as possible. That way it's nearly impossible to find any collision, ever. In addition to that, every user can choose how they want to verify it.

**Comment by notpeter** [comment]
Wide tables (SHA256 would be another 64 characters) and handling cases where we have checksums for some, but not all, hash algorithms gets ugly pretty quick. To support that I'd want to move to some machine readable format which is then rendered to a static page.

**Comment by dodekeract** [comment]
@notpeter [This script](https://github.com/severinkaderli/atom-reverser/blob/master/gulpfile.js) I wrote for a different project might help.

**Comment by hipunk** [comment]
sha1 is outdated as of today:

https://shattered.it/

Greetz

**Comment by dodekeract** [comment]
@hipunk Thanks for SHAr1ng.

**Comment by notpeter** [comment]
Thanks @hipunk.

SHA1's been outdated for a while, the question is whether it's broken for this particular use case.
It appears this particular hash collision attack is not universal, their example has them controlling content/structure of original document in order to be able to produce parallel documents which are altered in nature. But the writing is on the wall.

I'd be happy to move to SHA256, but back filling is the obvious concern.  Perhaps a display format which prefixes with algorithm in the table? Where it shows the best algorithm available (MD5 < SHA1 < SHA256). 

For the moment I'd prefer to stay away from SHA2 SHA384/SHA512 because they're hella long and SHA3 because it's still quite new.

**Comment by mark-chromium** [comment]
I have many of these images on hand and can back-fill. It’ll still be sparse, but it’d be a start at least.

**Comment by markmentovai** [comment]
For the [macOS 10.12.4 16E195](https://github.com/notpeter/apple-installer-checksums/commit/b372ad30d0891171b9ce6cdd9cf5de490d7816a5) and [Xcode 8.3 8E162](https://github.com/notpeter/apple-installer-checksums/commit/999c4c1844b3ef14b973fc3cedd26fc70ef3f357) hashes I just committed, I stuck the SHA-256 hashes in `<!-- comments -->` so that they’re at least preserved somewhere.

**Comment by dodekeract** [comment]
I found [a similar project](https://github.com/drduh/macOS-Security-and-Privacy-Guide/blob/master/InstallESD_Hashes.csv) which uses `.csv` to store hashes. Looks nice on GitHub.
