### ISSUE TITLE
Add checksums for official DMG files from Apple

### ISSUE THREAD

**Issue by gapf2010** [notpeter/apple-installer-checksums#130]
This link: https://support.apple.com/en-us/HT211683 contains (as of 2021-08-01) DMG downloads for OSX 10.10 and 10.11, as well as MacOS 10.12. Please add these checksums to the list:

SHA1(10.10-Yosemite/InstallMacOSX.dmg)= c542681961cc7fafb9c15bfd4af152a3a57f07fa
SHA1(10.11-El-Capitan/InstallMacOSX.dmg)= 21e45136e34c6f805e0f1977e38d6ff029a9a1e2
SHA1(10.12-Sierra/InstallOS.dmg)= 9ba989d30e3548341fc8f5847e856709cb5c67c2

Thanks!

**Comment by gapf2010** [comment]
I reinstalled my Macbook pro from scratch using the Snow Leopard DVD, and after fully updating it, I went to the Apple store and downloaded the OSX Lion installer. It downloaded correctly, but to my surprise, the sha1sum of the InstallESD.dmg file in the download is not here:

[gpulido@rhlaptop osx]$ sha1sum InstallESD.dmg 
3fae5fe16c7dda2c0fcc3afc49ec1724122a9617  InstallESD.dmg
[gpulido@rhlaptop osx]$ ls -l InstallESD.dmg 
-rw-r--r--. 1 gpulido gpulido 4719584394 Oct  9 13:06 InstallESD.dmg
[gpulido@rhlaptop osx]$ 

Can it be added to the list, please?

**Comment by 1alessandro1** [comment]
For Lion and Mountain Lion, the official builds which come from Apple's servers are the following:

- [Lion](https://support.apple.com/kb/DL2077?locale=en_GB): https://updates.cdn-apple.com/2021/macos/041-7683-20210614-E610947E-C7CE-46EB-8860-D26D71F0D3EA/InstallMacOSX.dmg

- [Mountain Lion](https://support.apple.com/kb/DL2076?locale=en_GB): https://updates.cdn-apple.com/2021/macos/031-0627-20210614-90D11F33-1A65-42DD-BBEA-E1D9F43A6B3F/InstallMacOSX.dmg

Users are encouraged to download and extract the installer on compatible machines, so that we can push the hashes from `InstallESD.dmg` or similar, since these images are only containers.

**Comment by Juesto** [comment]
Those packages should be possible to extract on any mac with tools such as suspicious package for InstallESD.dmg checksums.

**Comment by Juesto** [comment]
Suspicious Package should be able to.

**Comment by Juesto** [comment]
Lion: `79e39ccb6f8a8c40e500be55a9bf8de0275bd669`
Mountain Lion: `b8fa63882f06b52eb73f6ecc6661858de32e70e9`
i extracted it in catalina, it throws an error but pressing continue affects nothing, it does fully extract, disk mounter could verify it (should i use shasum or post hdiutil checksum?)

**Comment by Juesto** [comment]
@1alessandro1 sorry for the additional bump but pacifist indeed works after all.
