### ISSUE TITLE
What about macOSUpd10.13Supplemental.dmg? 

### ISSUE THREAD

**Issue by chethiya** [notpeter/apple-installer-checksums#30]
That can be downloaded from here : https://support.apple.com/kb/DL1937?locale=en_US

**Comment by Titokhan** [comment]
The project supports full ESD packages, not incremental minor updates. FYI, the build number of the supplemental package is 10.13.0 (17A405) and the full installer is already covered.

**Comment by markmentovai** [comment]
Incremental updaters are less of a priority, because they can easily be downloaded from Apple even after they’ve been superseded by subsequent updates. There isn’t any problem verifying authenticity when something comes right from Apple.

This isn’t true of the full OS installer images, which typically become difficult to verify once they’ve been superseded. The full OS installers and Xcode packages are also large enough that you might not want to invest the time to download new copies from Apple when you’ve already got a copy that just needs verification.

**Comment by chethiya** [comment]
Thanks for the explanation. I had to download it separately because App
Store couldn’t resume its download and it kept failing halfway through.
